version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 615299769479.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t khan-ecs-flask-app .
      - docker tag khan-ecs-flask-app:latest 615299769479.dkr.ecr.us-east-1.amazonaws.com/khan-ecs-flask-repo:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 615299769479.dkr.ecr.us-east-1.amazonaws.com/khan-ecs-flask-repo:latest
      - echo Writing image definitions...
      - printf '[{"name":"khan-container","imageUri":"615299769479.dkr.ecr.us-east-1.amazonaws.com/khan-ecs-flask-repo:latest"}]' > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
